task: detection

num_classes: 40
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ../../../dataset/seg_object_detection/auto_translate_v4-3/train
    ann_file: ../../../dataset/seg_object_detection/auto_translate_v4-3/train/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ../../../dataset/seg_object_detection/auto_translate_v4-3/valid
    ann_file: ../../../dataset/seg_object_detection/auto_translate_v4-3/valid/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False